id: P006684
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC387
  title: 'རི་ཆོས་མཚམས་ཀྱི་ཞལ་གདམས། '
  author: ''
  volumes:
    6ff175c1522b43878ddb734f9484936e:
      image_group_id: I2PD18241
      title: ''
      volume_number: 1
      total_pages: 528
