id: P006684
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1AC387
  title: 'རི་ཆོས་མཚམས་ཀྱི་ཞལ་གདམས། '
  author: ''
  volumes:
    6ff175c1522b43878ddb734f9484936e:
      image_group_id: I2PD18241
      title: ''
      volume_number: 1
      total_pages: 528
      base_file: v001.txt
